theme: jekyll-theme-tactile

exclude: ["README.md"]

title: Parlez-vous Singlish?
description: Comment communique-t-on dans une ville qui a quatre langues officielles et une dizaine de langues ou dialectes inofficielles ? 

